import { canvas } from '../canvas';
import {
  LEVEL_THEMES,
  mapGenerator,
  Level,
  NB_OF_TILES_HORIZONTALLY,
  NB_OF_TILES_VERTICALLY,
  rowGenerator,
  TileType,
} from './level-type';

import { endNpc } from '../NPC';
import { thirdEnemy } from '../enemy';

export const level_3: Level[] = [
  {
    map: [
      '■                               ',
      '■                               ',
      '■                               ',
      '■                               ',
      '■                               ',
      '■                               ',
      '■                               ',
      '■.                              ',
      '■                               ',
      '■                               ',
      '■                               ',
      '■                               ',
      '■                               ',
      '■                               ',
      '■                               ',
      '■                               ',
      '■                               ',
      'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
    ],
  },
  {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                          ■■■■■■',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '    ■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
      'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
    ],
    npc: endNpc,
  },
  {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                           ■■■  ',
      '                                ',
      '                                ',
      '              ■■■■■■            ',
      '                                ',
      '                                ',
      '                                ',
      '■■■■■■■■■                  ■■■  ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '              ■■■               ',
      'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
    ],
  },
  {
    map: [
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '                                ',
      '              ■■■■──────────────',
      '                                ',
      '                                ',
      '                                ',
      '    ■■■                         ',
      '                                ',
      '                                ',
      '                                ',
      '──────────────.                 ',
      '              ■■■               ',
      'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
    ],
  },
  {
    getMap() {
      return [
        '■                              ■',
        '■                              ■',
        '■                              ■',
        '■                              ■',
        '■                              ■',
        '■                              ■',
        '■                              ■',
        '■■■■                       ■■■■■',
        '■                              ■',
        '■                              ■',
        '■     ■■■             ■■■      ■',
        '■                              ■',
        '■                              ■',
        '■                              ■',
        '■               E              ■',
        '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
        '                                ',
        'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
      ].map((row, index) =>
        thirdEnemy.isDead &&
        thirdEnemy.diedAt < Date.now() - 2000 &&
        index < NB_OF_TILES_VERTICALLY - 3
          ? rowGenerator(' ')
          : row
      );
    },
    enemy: thirdEnemy,
  },
  {
    map: [
      '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
      '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
      '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
      '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
      '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
      '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
      '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
      '            |   |   |           ',
      '            |   |   |           ',
      '            |   |   |           ',
      '            |   |   |           ',
      '            |   |   |           ',
      '            |   |   |           ',
      '            |   |   |           ',
      '            |   |   |      P    ',
      '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
      '                                ',
      'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
    ],
    npc: endNpc,
  },
  // {
  //   map: [
  //     '       ■■■■■ ■   ■ ■■■■■        ',
  //     '         ■   ■   ■ ■            ',
  //     '         ■   ■■■■■ ■■■■         ',
  //     '         ■   ■   ■ ■            ',
  //     '         ■   ■   ■ ■■■■■        ',
  //     '                                ',
  //     '       ■■■■■ ■   ■ ■■■■         ',
  //     '       ■     ■■  ■ ■   ■        ',
  //     '       ■■■■  ■ ■ ■ ■   ■        ',
  //     '       ■     ■  ■■ ■   ■        ',
  //     '       ■■■■■ ■   ■ ■■■■         ',
  //     '                                ',
  //     '                                ',
  //     '                                ',
  //     '                                ',
  //     '■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■',
  //     '                                ',
  //     'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL',
  //   ],
  // },
].map((level, index) => ({
  ...level,
  get map() {
    return level.map ?? level.getMap();
  },
  position: { x: index, y: 3 },
  ...LEVEL_THEMES.lava,
  music: 'platforming',
}));
